// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znkqgcbmzwqibbouvfcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpua3FnY2JtendxaWJib3V2ZmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxODc5OTUsImV4cCI6MjA2MTc2Mzk5NX0.HVkKzKrhMeVqhMlxRAEIvdtwFMWgMTxWUUq8ki5kKs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);